### PR TITLE
Detect and collect deprecated fields in the check

### PR DESCRIPTION
**Pull request by janvhs**
This PR allows to collect and show deprecations in the checks.  For more information and reasoning behind changes, have a look at the commit message. (I wish I could just tell GitHub to throw these in here)

### CODE REVIEW

**Review by dottorblaster — COMMENTED** [review]
I like the approach catching _every_ deprecated field, I would have aimed for something way simpler. Also, I would prefer the deprecation thing to be another validator, not modifying too much what we already had in place.

Can you fix the tests?

**Review by gagandeepb — COMMENTED** [review]
1. Have you considered locking down on a more recent jsonschema meta-schema version ? I understand more recent versions have a richer validation/schema-evolution capabilities. 
2. I wonder if it's interesting/feasible to express deprecation of fields using the [schema-evolution capabilities of more recent versions.](https://json-schema.org/draft/2019-09/json-schema-validation#rfc.section.9.3) :thinking:

**Comment by gagandeepb** [comment]
I was not suggesting to update the crate, necessarily. However, I am/was under the impression that more recent versions of the json schema spec (not the crate, but the "dialect" that a specific schema instantiation adheres to) support field-level deprecation (according to the link I shared previously). I also understand that newer versions of the jsonschema crate support newer dialects (like draft2020, draft2019, etc.) but I am not fully aware of specific dialect support/conformance limitations of the current jsonschema crate. Concretely, I was wondering :
1. If updating the schema dialect of the underlying checks DSL spec, and
2. If marking specific fields in the DSL spec as deprecated, and
3. If handling 1 and 2 here in this repo (i.e. tlint) by making use of whichever implementation of json schema validation that appropriately conforms to the dialect that supports field-deprecation at the schema level. ...
... is something that is feasible/interesting to evaluate for the purposes here?

**Comment by gagandeepb** [comment]
> > If marking specific fields in the DSL spec as deprecated, and

> I don't think it is wise to have multiple sources of truth

Indeed it is not, I agree. But how is marking specific fields in the DSL spec as deprecated an instance of multiple sources of truth? Isn't the spec supposed to be the source of truth and tlint the "verifier"/checker of an instantiation of a check against the spec?

**Review by dottorblaster — APPROVED** [review]

**Pull request merged**
